const fakeDepartData = [
  {
    date: 'date!',
    cycle: 'cycle!',
    departments: {
      id: ' ',
      score: ' ',
      severity: 2,
      entities: [
        { id: 'pplId', label: 'pplLabel', score: 93, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 43, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 53, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 83, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 }
      ]
    }
  },
  {
    date: 'date!',
    cycle: 'cycle!',
    departments: {
      id: ' ',
      score: ' ',
      severity: 2,
      entities: [
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 }
      ]
    }
  },
  {
    date: 'date!',
    cycle: 'cycle!',
    departments: {
      id: ' ',
      score: ' ',
      severity: 2,
      entities: [
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 }
      ]
    }
  },
  {
    date: 'date!',
    cycle: 'cycle!',
    departments: {
      id: ' ',
      score: ' ',
      severity: 2,
      entities: [
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 }
      ]
    }
  },
  {
    date: 'date!',
    cycle: 'cycle!',
    departments: {
      id: ' ',
      score: ' ',
      severity: 2,
      entities: [
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 }
      ]
    }
  },
  {
    date: 'date!',
    cycle: 'cycle!',
    departments: {
      id: ' ',
      score: ' ',
      severity: 2,
      entities: [
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 }
      ]
    }
  },
  {
    date: 'date!',
    cycle: 'cycle!',
    departments: {
      id: ' ',
      score: ' ',
      severity: 2,
      entities: [
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 }
      ]
    }
  },
  {
    date: 'date!',
    cycle: 'cycle!',
    departments: {
      id: ' ',
      score: ' ',
      severity: 2,
      entities: [
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 }
      ]
    }
  },
  {
    date: 'date!',
    cycle: 'cycle!',
    departments: {
      id: ' ',
      score: ' ',
      severity: 2,
      entities: [
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 }
      ]
    }
  },
  {
    date: 'date!',
    cycle: 'cycle!',
    departments: {
      id: ' ',
      score: ' ',
      severity: 2,
      entities: [
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 },
        { id: 'pplId', label: 'pplLabel', score: 23, num_alerts: 10, severity: 4 }
      ]
    }
  }
]

export default function (state = fakeDepartData, action) {
    switch (action.type) {
        
        case 'RANGER_ACT':
            for(var i=0; i<fakeDepartData[0].departments.entities.length; i++){
              fakeDepartData[0].departments.entities[i]["score"]=Math.random()*100;
            }
            return fakeDepartData
        default:
            return state
    }
}
